import {abilityStatus,createDefaultAbilityHotbarSettings,moveAbilitySlot,orderedAbilities,restoreAbilityOrder,saveAbilityHotbarSettings} from './ability-hotbar-data.js?v=29a8-kinetic-combat-20260729';

export const HOTBAR_INFO_HOLD_MS=460;
export function hotbarPrompt(input,side,entry,device=input?.lastInputDevice?.[side-1]||'keyboard',slot=1){if(device==='touch')return'TAP';if(device==='keyboard'||device==='mouse')return String(slot);return input?.actionLabel?.(side,'u',{device:'controller'})||'ACTIVATE'}

export class AbilityHotbar{
  constructor({root,input,settings=createDefaultAbilityHotbarSettings(),getFighter=()=>null,getWorld=()=>null,getDevice=()=> 'keyboard',notify=()=>{},onChange=()=>{},onInfo=()=>{},onInfoClose=()=>{}}={}){this.root=root;this.input=input;this.settings=settings;this.getFighter=getFighter;this.getWorld=getWorld;this.getDevice=getDevice;this.notify=notify;this.onChange=onChange;this.onInfo=onInfo;this.onInfoClose=onInfoClose;this.fighterId='';this.signature='';this.selectedSlot=1;this.hold=null;this.drag=null;this.slotRoot=root?.querySelector?.('[data-hotbar-slots]');this.info=root?.querySelector?.('[data-hotbar-info]');this.customize=root?.querySelector?.('[data-hotbar-customize]');this.customize?.addEventListener('click',()=>this.root?.dispatchEvent?.(new CustomEvent('hotbarcustomize',{bubbles:true})));this._bind();this.configure(settings)}
  _bind(){this.slotRoot?.addEventListener('pointerdown',event=>this.pointerDown(event));this.slotRoot?.addEventListener('pointerup',event=>this.pointerUp(event));this.slotRoot?.addEventListener('pointercancel',()=>this.cancelHold());this.slotRoot?.addEventListener('pointermove',event=>this.pointerMove(event));}
  configure(settings){this.settings=createDefaultAbilityHotbarSettings(settings);if(!this.root)return;this.root.dataset.display=this.settings.desktop;this.root.dataset.text=this.settings.text;this.root.dataset.size=this.settings.size;this.root.dataset.cooldown=this.settings.cooldown;this.root.style.setProperty('--hotbar-opacity',this.settings.opacity);this.root.style.setProperty('--hotbar-scale',this.settings.size==='custom'?this.settings.customScale:1);this.root.style.setProperty('--hotbar-offset-x',`${this.settings.offsetX}px`);this.root.style.setProperty('--hotbar-offset-y',`${this.settings.offsetY}px`);this.root.classList.toggle('hotbar-unlocked',!this.settings.locked);this.render(true)}
  setFighter(id){if(this.fighterId===id)return;this.fighterId=id||'';this.selectedSlot=Math.max(1,Math.min(this.selectedSlot,this.entries().length||1));this.signature='';this.render(true)}
  setVisible(visible,touch=false){this.root?.classList?.toggle('hidden',!visible);this.root?.classList?.toggle('touch-hotbar',!!touch)}
  entries(){return orderedAbilities(this.fighterId,this.settings).slice(0,5)}
  render(force=false){if(!this.root||!this.slotRoot||!this.fighterId)return;const fighter=this.getFighter(),world=this.getWorld(),device=this.getDevice(),entries=this.entries();this.selectedSlot=Math.max(1,Math.min(this.selectedSlot,entries.length||1));const models=entries.map((entry,index)=>({entry,status:abilityStatus(fighter,entry,world),prompt:hotbarPrompt(this.input,1,entry,device,index+1)}));const signature=JSON.stringify(models.map((model,index)=>[model.entry.id,model.status.cooldownText,model.status.activeText,model.status.available,model.status.hpWarning,model.prompt,this.settings.text,this.settings.cooldown,index+1===this.selectedSlot]));if(!force&&signature===this.signature)return;this.signature=signature;
    this.slotRoot.innerHTML=models.map(({entry,status,prompt},index)=>{const selected=index+1===this.selectedSlot;return`<button class="abilitySlot ${status.available?'':'unavailable'} ${status.active?'active':''} ${selected?'selected':''}" data-ability-id="${entry.id}" data-slot="${index+1}" aria-label="Slot ${index+1}: ${entry.label}" aria-disabled="${!status.available}" aria-current="${selected?'true':'false'}"><span class="abilityCooldownFill" style="--cooldown-fill:${Math.round(status.fill*100)}%"></span><span class="abilityNumber">${prompt}</span><span class="abilityIcon">${entry.icon}</span><span class="abilityName">${this.settings.text==='short'?entry.short:entry.label}</span><span class="abilityCost">${entry.energy} EN${entry.hp?` • ${entry.hp} HP`:''}</span><span class="abilityState">${status.activeText||status.cooldownText||status.hpWarning||(!status.available?status.reason:'READY')}</span></button>`}).join('');
  }
  update(){this.render(false)}
  activateSlot(slot,device=this.getDevice()){this.selectSlot(slot);const entry=this.entries()[Number(slot)-1],fighter=this.getFighter();if(!entry||!fighter)return false;const status=abilityStatus(fighter,entry,this.getWorld());if(!status.available){this.notify(status.reason||'Ability unavailable',{key:`hotbar-${entry.id}`});return false}this.input?.queueGameplayAction?.(1,entry.action,device);return true}
  selectSlot(slot){const count=this.entries().length||1,next=Math.max(1,Math.min(Number(slot)||1,count));if(next===this.selectedSlot)return false;this.selectedSlot=next;this.signature='';this.render(true);return true}
  moveSelection(direction){const count=this.entries().length;if(!count)return false;const next=((this.selectedSlot-1+Number(direction||0))%count+count)%count+1;return this.selectSlot(next)}
  activateSelected(device=this.getDevice()){return this.activateSlot(this.selectedSlot,device)}
  pointerDown(event){const button=event.target.closest('[data-ability-id]');if(!button)return;event.preventDefault();event.stopPropagation();button.setPointerCapture?.(event.pointerId);if(!this.settings.locked){this.drag={id:button.dataset.abilityId,pointerId:event.pointerId,target:Number(button.dataset.slot)-1};button.classList.add('dragging');return}this.cancelHold();this.hold={button,pointerId:event.pointerId,shown:false,timer:setTimeout(()=>{if(!this.hold)return;this.hold.shown=true;this.showInfo(button.dataset.abilityId,Number(button.dataset.slot));},HOTBAR_INFO_HOLD_MS)}}
  pointerMove(event){if(!this.drag||this.drag.pointerId!==event.pointerId)return;const target=this.root?.ownerDocument?.elementFromPoint?.(event.clientX,event.clientY)?.closest?.('[data-slot]');if(target)this.drag.target=Number(target.dataset.slot)-1}
  pointerUp(event){if(this.drag&&this.drag.pointerId===event.pointerId){const{id,target}=this.drag;this.slotRoot?.querySelector('.dragging')?.classList.remove('dragging');this.drag=null;if(moveAbilitySlot(this.settings,this.fighterId,id,target)){saveAbilityHotbarSettings(this.settings);this.onChange(this.settings);this.render(true)}return}if(!this.hold||this.hold.pointerId!==event.pointerId)return;event.preventDefault();const{button,shown}=this.hold;this.cancelHold();if(!shown){if(this.settings.activation==='double'){const now=Date.now(),last=Number(button.dataset.lastTap||0);button.dataset.lastTap=String(now);if(now-last>380){this.notify('DOUBLE TAP TO ACTIVATE',{key:`double-${button.dataset.abilityId}`});return}}const entry=this.entries()[Number(button.dataset.slot)-1];if(this.settings.activation==='confirm-ultimate'&&entry?.ultimate&&!confirm(`Activate ${entry.label}?`))return;this.activateSlot(button.dataset.slot,'touch')}}
  cancelHold(){if(this.hold?.timer)clearTimeout(this.hold.timer);this.hold=null}
  showInfo(id,slot){const entry=this.entries().find(item=>item.id===id);if(!entry||!this.info)return;const prompt=hotbarPrompt(this.input,1,entry,this.getDevice(),slot);this.info.innerHTML=`<strong>${entry.label}</strong><p>${entry.description}</p><dl><div><dt>Binding</dt><dd>${prompt}</dd></div><div><dt>Energy</dt><dd>${entry.energy}</dd></div>${entry.hp?`<div><dt>HP cost</dt><dd>${entry.hp} (floor 1)</dd></div>`:''}<div><dt>Cooldown</dt><dd>${entry.cooldown?`${Math.round(entry.cooldown/60)}s`:'—'}</dd></div>${entry.restriction?`<div><dt>Restriction</dt><dd>${entry.restriction}</dd></div>`:''}</dl><button data-hotbar-info-close>CLOSE</button>`;this.info.classList.remove('hidden');this.info.querySelector('[data-hotbar-info-close]').onclick=()=>{this.info.classList.add('hidden');this.onInfoClose(entry)};this.onInfo(entry)}
  restoreDefaults(){restoreAbilityOrder(this.settings,this.fighterId);saveAbilityHotbarSettings(this.settings);this.onChange(this.settings);this.render(true)}
  moveSelected(id,direction){const entries=this.entries(),index=entries.findIndex(entry=>entry.id===id);if(index<0)return false;const moved=moveAbilitySlot(this.settings,this.fighterId,id,index+direction);if(moved){saveAbilityHotbarSettings(this.settings);this.onChange(this.settings);this.render(true)}return moved}
}
