export const BUILD_VERSION='Prototype 2.9A.17 — Chapter 1–3 Repair';
export const SAVE_SCHEMA_VERSION=261;
export const BUILD_FEATURES=Object.freeze([
  'responsive-no-overlap-touch-layout','portrait-safe-control-zone','short-phone-mode-layout',
  'touch-first-menu-prompts','swipe-cued-classic-settings','comfortable-touch-targets',
  'unified-chapter-controls','shared-chapter-1-2-3-story-engine','automatic-story-chaining','rrvvfo-story-only-release-ui',
  'six-chapter-classic-and-arena-unlocks','hidden-pre-clear-modes','quick-continue-unlock-guard',
  'artifact-cleaned-core-fighter-atlases','tangai-dojo-visual-overhaul','rrvvfo-hub-camera-follow','hub-camera-occlusion-avoidance',
  'sage-36-pose-production-atlas','atlas-backed-roster-portraits','classic-fighter-readability-scale',
  'six-chapter-story-progress-meter','frame-rate-independent-hub-actors','startup-progress-rollback','compact-round-banners',
  'main-menu-visible-groups','device-aware-menu-prompts','rrvvfo-route-portrait','story-rpg-menu','shot-power-trick-signs',
  'chapter-1-direct-attempt-counter','chapter-1-tutorial-checkpoints','chapter-1-quick-refresher','confirmed-tutorial-grab',
  'living-tournament-road','optional-road-fight-exit','consistent-story-energy','device-aware-exploration-prompts',
  'chapter-2-rpg-levels','story-hp-power-defense-speed-focus','level-scaled-tournament-enemies','visible-boss-hp-bonus',
  'chapter-2-living-hub','mandatory-hub-quest-spine','optional-side-quests','tournament-intermissions','plouke-rumor-thread',
  'bark-and-wade-sprite-atlases','story-and-arena-sprite-integration','tournament-opening-ceremony','hailey-plouke-preliminary',
  'hamual-power-test','daniel-skill-test','phased-bark-pouki-set-piece','playable-plouke-studies','quiet-final-preparation',
  'milestone-enemy-levels','mechanics-verified-dummy','wade-race-countdown-splits','nearby-npc-chatter','performance-based-plouke-rewards',
  'persistent-side-quest-stat-rewards','wade-route-race','bark-ring-repair','controlled-flame-minigame','district-navigation',
  'chapter-2-story-assist','persistent-tournament-run-refusal','try-to-beat-plouke-objective','unified-story-overlays',
  'three-visible-bracket-cards','announcer-quest-save-recovery','sage-atlas-backed-hub-npc',
  'full-chapter-3-investigation','after-hours-tournament-hub','three-mandatory-chapter-3-side-stories','ten-optional-chapter-3-quests',
  'bracket-record-reconstruction','locked-night-shift-route','plouke-bag-investigation','lens-energy-trail',
  'abandoned-resonance-facility','auxiliary-power-puzzle','recorded-attack-corridor','runaway-training-dummy',
  'subject-r-files','unfinished-echo-boss','project-hollow-discovery','object-swap-security-door','remote-highlands-ending',
  'dynamic-objective-compass','investigation-ability-feedback','chapter-3-autosave-checkpoints',
  'chapter-3-title-transition','living-story-hubs','story-menu-manual-tracker-keys','consistent-completion-language',
  'unique-arena-normal-profiles','kinetic-movement','launch-pursuit-system','arena-combo-scaling','juggle-protection',
  'visible-ringout-fall','three-hit-edge-pressure','shot-power-trick-techniques','momentum-finisher','fair-story-health',
  'keyboard-mouse-controller-touch','showcase-sprites','sage-manual','arena-training','uploaded-site-icon','installable-web-icons'
]);
