export const BUILD_VERSION='Prototype 2.9A.8 — Kinetic Combat Pass';
export const SAVE_SCHEMA_VERSION=245;
export const BUILD_FEATURES=Object.freeze([
  'combat-2.9A','controller-mobile','rrvvfo-sprites-v2','revvfo-sprites','qol-2.3.5b',
  'arena-pipeline','lost-year-story','mission-0','mission-1-tutorial','mission-2-full-tournament',
  'sonic-battle-dialogue','sprite-on-top-dialogue','scoped-menu-theme','horizontal-mode-select',
  'character-route-select','six-chapter-rrvvfo-roadmap','sa1-style-route-discovery','automatic-story-chaining','chapter-select',
  'persistent-combat-manual','manual-page-discovery','rrvvfo-manual-reactions','manual-save-repair',
  'living-training-grounds','playable-tournament-road','field-object-swap','field-shots-of-agony',
  'roaming-fight-choice','escape-qte','field-lens-of-truth','free-explore-road-replay',
  'hub-facing-correction','permanent-river-collision','physical-swap-rock','dojo-warmup-loop',
  'field-fire-roadblock','expanded-road-dialogue','expanded-roaming-npcs','tournament-checkpoint-scene',
  'chapter-2-open-hub','chapter-2-living-npcs','sage-disappearance','training-level-system',
  'optional-bark-spar','optional-grunt-fights','story-fight-run-joke','full-local-tournament-bracket',
  'rrvvfo-vs-wade','bark-vs-pouki-spectator-fight','plouke-final','programmed-story-loss',
  'fire-awakening-countdown','interactive-beam-clash','beam-clash-win-ringout-ending','plouke-sage-reveal',
  'explicit-chapter-replay-buttons','isolated-replay-save-state','replay-xp-lock','chapter-2-transparent-overlay-fix',
  'first-to-three-ko-combat','continuous-winner-state','instant-ko-respawn','no-timeout-ko-rules',
  'timed-guard-and-perfect-parry','manual-energy-charge','standing-guard-recovery','grab-system','heavy-clashes','projectile-clashes',
  'state-based-non-cheating-ai','difficulty-aware-arena-ai','wade-complete-arena-kit','bark-complete-arena-kit','pouki-rushdown-ai','plouke-sage-ai',
  'official-tournament-ring-outs','optional-fights-no-ringouts','ringout-manual-tutorial','ring-edge-warning','instant-zero-zero-story-rematch',
  'physical-earth-walls','rock-projectile-counter','lens-prediction-mastery','mastered-lens-two-auto-dodges',
  'shots-of-agony-all-energy','rebalanced-solar-weave','continuous-road-ko-respawn','shared-story-level-stats','working-energy-control',
  'story-startup-error-screen','dialogue-skip-confirmation','exit-restart-confirmations','forced-landscape-story',
  'story-mobile-menu-repair','story-minimap','fullscreen-story-map','objective-compass','exploration-hud-mode',
  'chapter2-story-menu','chapter2-clear-combat-hud','chapter2-progression-in-menu',
  'shared-chapter-1-2-3-story-engine','unified-story-input-modes','unified-story-hud-modes','unified-story-dialogue-presentation',
  'guided-eight-step-combat-tutorial','live-tutorial-checklist','tutorial-control-highlights','tutorial-inactivity-help','fixed-charge-step','fixed-lens-final-step','tutorial-restart-repair',
  'chapter3-progress-restore','chapter3-development-preview','expanded-training-region','nonlinear-investigation-hub',
  'unified-story-runtime-adoption','single-story-runtime-controller','shared-story-command-filter','shared-story-hud-controller','shared-story-transition-api','dialogue-lifecycle-cleanup','legacy-mobile-overlay-suppression','tutorial-focus-safe-ability-locks','tutorial-success-detection','adaptive-tutorial-prompts','tutorial-progressive-ability-unlocks','tutorial-clean-hud','landscape-main-menu-repair','mobile-route-details-modal','design-token-foundation','animated-title-presentation','menu-character-silhouettes','arcade-3x-tooltip','task-based-loading-progress','procedural-original-menu-dojo-tournament-music','consistent-perfect-parry-presentation','fighter-development-status','sage-manual-public-guide','training-suggested-drills','single-release-cache-id','plain-story-section-labels','multiple-blocked-routes','npc-clue-tracking','strange-man-lead','underground-base-entrance','chapter-controls-source-of-truth','shared-mouse-semantic-input','mouse-tutorial-prompts',
  'casual-quick-battle','fair-100-hp-cpu','finished-roster-filter','truthful-lens-predictions','reduced-lens-cost',
  'compact-manual-unlocks','movement-jump-dash-warmup','road-escape-retry','first-to-one-road-fight','dedicated-interact-action',
  'device-aware-exploration-prompts','arena-training-default','classic-training-advanced-lab','guard-fatigue-warning','selected-ability-hotbar',
  'simplified-fighter-setup','advanced-settings-collapse','touch-hotbar-safe-layout','tutorial-grab-range-assist','tutorial-grab-confirmed-hit-detection',
  'unique-arena-normal-profiles','kinetic-movement-pass','launch-pursuit-system','one-pursuit-per-combo','arena-combo-scaling','six-hit-juggle-protection',
  'visible-ringout-fall','three-hit-edge-pressure','non-grab-ringout-finishers','dash-dodge-window','depth-readability-trails','anti-stall-energy-rules',
  'counter-cost-and-cooldown','breaker-cost-and-cooldown','45-starting-energy','ability-startup-and-recovery','shot-power-trick-categories','momentum-finisher','favicon'
]);
