import {DEFAULT_QOL_SETTINGS,SETTINGS_CATEGORIES,categoryDefaults,sanitizeQolSettings} from './qol-settings.js?v=29a28p1-mobile-hub-space-20260730';

const FIELDS={
  Gameplay:[['combatMessages','Combat Messages','select',['full','important','off']],['hubCamera','Hub Free Camera','select',['drag','off']],['hubCameraSensitivity','Camera Look Sensitivity','rangeScale'],['resetHubCamera','Reset Hub Camera','action'],['firstTimeHints','First-time Hints','check'],['resetHints','Reset Hints','action'],['holdConfirm','Hold Confirmation for Restarts','check'],['skipAnimations','Skip Menu Animations','check'],['reducedMotion','Reduced Menu Motion','check'],['showQuickContinue','Show Quick Continue','check']],
  Audio:[['master','Master Volume','range'],['music','Music Volume','range'],['sfx','Sound Effects Volume','range'],['ui','UI Volume','range'],['voice','Voice Volume (Future Voice Acting)','rangeFuture'],['mute','Mute All','check'],['audioTest','Audio Test','action']],
  Video:[['quality','Video Preset','select',['low','medium','high','automatic']],['backgroundMotion','Background Motion','select',['full','reduced','off']],['spriteSmoothing','Sprite Smoothing','check']],
  Accessibility:[['cameraShake','Camera Shake','select',['full','reduced','off']],['impactFreeze','Impact Freeze / Hitstop','select',['full','reduced','off']],['screenFlash','Screen Flash','select',['full','reduced','off']],['hitFlash','Hit Flash','select',['full','reduced','off']],['ultimateEffects','Ultimate Effects','select',['full','reduced']],['lensOverlay','Lens Blindness Overlay','select',['standard','reduced']],['highContrastHud','High-contrast HUD','check'],['largerHudText','Larger HUD Text','check'],['strongOutlines','Stronger Player Outlines','check']],
  HUD:[['mode','HUD Layout','select',['full','compact','minimal','auto']]],
  'Ability Hotbar':[['desktop','Desktop Ability Hotbar','select',['full','compact','cooldowns','hidden']],['text','Hotbar Text','select',['full','short','icons']],['size','Hotbar Size','select',['small','medium','large','custom']],['customScale','Custom Hotbar Scale','rangeScale'],['cooldown','Cooldown Display','select',['number','fill','both']],['activation','Ability Activation','select',['tap','double','confirm-ultimate']],['opacity','Hotbar Opacity','rangeScale'],['locked','Lock Hotbar Order','check'],['pauseForInfo','Pause Single-player for Move Info','check'],['restoreHotbar','Restore Character Defaults','action']],
  Developer:[['fps','FPS Display','check']],
  Controls:[['controllerTest','Test Controller','action'],['controllerStyle','Change Controller Style','action']],
  'Touch Controls':[['touchPanel','Open Touch Layout Settings','action']],
  Controller:[['controllerTest','Test Controller','action'],['controllerReconnect','Controller Assignment & Reconnect','action']],
  'Save Data':[['exportSave','Export Save','action'],['importSave','Import Save','action'],['resetSettings','Reset Settings Only','action'],['resetTraining','Reset Training Presets','action'],['resetAll','Reset All Data','action']]
};
const categoryKey=category=>category.toLowerCase().replaceAll(' ','');
const pathFor=category=>({gameplay:'gameplay',audio:'audio',video:'video',accessibility:'accessibility',hud:'hud',abilityhotbar:'hotbar',developer:'developer'})[categoryKey(category)];
const OPTION_LABELS={drag:'Click and Drag',off:'Off'};
const label=value=>OPTION_LABELS[value]||String(value).replaceAll(/([A-Z])/g,' $1').replace(/^./,character=>character.toUpperCase());

export class SettingsPanel{
  constructor(root,{settings,onApply=()=>{},onAction=()=>{}}={}){this.root=root;this.settings=sanitizeQolSettings(settings);this.draft=sanitizeQolSettings(settings);this.onApply=onApply;this.onAction=onAction;this.category='Gameplay';this.dirty=false;this.categories=root?.querySelector('#settingsCategories');this.content=root?.querySelector('#settingsContent');this.categories?.addEventListener('click',event=>{const button=event.target.closest('[data-settings-category]');if(button){this.category=button.dataset.settingsCategory;this.render()}});this.content?.addEventListener('input',event=>this.change(event));this.content?.addEventListener('click',event=>{const button=event.target.closest('[data-settings-action]');if(button)this.onAction(button.dataset.settingsAction)});this.render()}
  open(category='Gameplay'){this.category=category;this.draft=sanitizeQolSettings(this.settings);this.dirty=false;this.render();this.root?.classList.remove('hidden')}
  close({discard=true}={}){if(discard)this.draft=sanitizeQolSettings(this.settings);this.dirty=false;this.root?.classList.add('hidden')}
  apply(){this.settings=sanitizeQolSettings(this.draft);this.dirty=false;this.onApply(this.settings);return this.settings}
  resetCategory(){const path=pathFor(this.category),defaults=categoryDefaults(this.category);if(path&&defaults){this.draft[path]=defaults;if(this.category==='Gameplay')this.draft.menu=JSON.parse(JSON.stringify(DEFAULT_QOL_SETTINGS.menu));this.dirty=true;this.render()}}
  resetAll(){this.draft=sanitizeQolSettings(DEFAULT_QOL_SETTINGS);this.dirty=true;this.render()}
  change(event){const control=event.target.closest('[data-setting]');if(!control)return;let path=pathFor(this.category),key=control.dataset.setting;if(this.category==='Gameplay'&&key in this.draft.menu)path='menu';if(!path)return;let value=control.type==='checkbox'?control.checked:control.value;if(control.type==='range')value=Number(value);this.draft[path][key]=value;this.dirty=true;const output=control.parentElement.querySelector('output');if(output)output.textContent=control.dataset.scale==='true'?`${Math.round(value*100)}%`:`${value}%`}
  render(){if(!this.root)return;this.categories.innerHTML=SETTINGS_CATEGORIES.filter(category=>category!=='Developer'||location.hostname==='localhost'||location.search.includes('developer=1')).map(category=>`<button data-settings-category="${category}" class="${category===this.category?'active':''}">${category}</button>`).join('');const path=pathFor(this.category),values=this.category==='Gameplay'?{...this.draft.gameplay,...this.draft.menu}:path?this.draft[path]:{};this.content.innerHTML=(FIELDS[this.category]||[]).map(([key,name,type,options])=>{if(type==='action')return`<button class="secondary" data-settings-action="${key}">${name}</button>`;if(type==='check')return`<label>${name}<input type="checkbox" data-setting="${key}" ${values[key]?'checked':''}></label>`;if(type==='rangeFuture'){const value=values[key];return`<label class="futureSetting">${name} <output>${value}%</output><input type="range" value="${value}" min="0" max="100" disabled><small>Reserved for the future voice-acting update.</small></label>`}if(type==='range'||type==='rangeScale'){const scale=type==='rangeScale',value=values[key],minimum=key==='hubCameraSensitivity'?'.4':key==='customScale'?'.7':key==='opacity'?'.35':'.6',maximum=key==='hubCameraSensitivity'?'1.6':key==='customScale'?'1.45':'1';return`<label>${name} <output>${scale?Math.round(value*100):value}%</output><input type="range" data-setting="${key}" ${scale?`data-scale="true" min="${minimum}" max="${maximum}" step=".05"`:'min="0" max="100" step="1"'} value="${value}"></label>`}return`<label>${name}<select data-setting="${key}">${options.map(option=>`<option value="${option}" ${values[key]===option?'selected':''}>${label(option)}</option>`).join('')}</select></label>`}).join('')||'<p>This category uses its dedicated configuration panel.</p>'}
}
