import {ROSTER,ROSTER_IDS,isMirrorMatch} from '../js/roster.js';
import {InputManager} from '../js/input.js';
import {ATTACKS,Projectile,TimerRegistry,calculateFinalDamage,resetCombo} from '../js/combat.js';
import {EffectSystem} from '../js/effects.js';
import {Fighter} from '../js/fighter.js';
import {CHARACTER_AI,aiProfile,availableAIActions,decideCPU,selectAIAction} from '../js/ai.js';
import {MOVESETS,MOVE_DAMAGE_TOTALS,moveFor} from '../js/movesets.js';
import {trainingState,resetTrainingClash,resetTrainingWorld,exitTrainingWorld,setTrainingSetting,dummyCommand} from '../js/training.js';
import {CLASH_BALANCE,clearClash,compatibleMeleeClash,cpuClashContribution,createClashState,finishClash,startClash,tryProjectileClash,updateClash} from '../js/clash-system.js';
import {DEFENSE_BALANCE} from '../js/guard-system.js';
import {createCameraState} from '../js/camera-system.js';
import {ULTIMATE_BALANCE,ULTIMATES,beginCinematicUltimate,clearCinematic,createCinematicState,updateCinematic} from '../js/ultimate-system.js';
import {AUDIO_HOOKS} from '../js/audio-manager.js';

const results=[],assert=(condition,message)=>{if(!condition)throw new Error(message)};
async function test(name,fn){try{await fn();results.push({name,pass:true})}catch(error){results.push({name,pass:false,error:error.message})}}
function makeWorld(){
  Object.assign(trainingState,{enabled:false,infiniteHealth:false,infiniteEnergy:false,infiniteGuard:false,guardRegen:true,infiniteClash:false,forceNextClash:false,dummy:'never',stationaryBlock:false,afterFirstHit:false});
  const world={width:960,height:540,ground:430,fighters:[],projectiles:[],effects:new EffectSystem(),timers:new TimerRegistry(),clash:createClashState(),camera:createCameraState(),cinematic:createCinematicState(),cinematicMode:'off',localMode:false,reducedShake:false,shake:0,hitstop:0,training:trainingState,sound:()=>{}};
  world.tryProjectileClash=tryProjectileClash;return world;
}
function pair(a='rrvvfo',b='revvfo',world=makeWorld()){const one=new Fighter(a,1,false,world),two=new Fighter(b,2,false,world);world.fighters=[one,two];one.x=300;two.x=345;return{world,one,two}}
class ManualTimers{constructor(){this.tasks=[]}schedule(fn,delay){this.tasks.push({fn,delay})}cancelAll(){this.tasks=[]}flush(){for(const task of this.tasks.splice(0))task.fn()}get size(){return this.tasks.length}}

await test('loads the complete roster',()=>assert(ROSTER_IDS.length===15,`expected 15, got ${ROSTER_IDS.length}`));
await test('preserves mirror-match restriction',()=>{assert(isMirrorMatch('rrvvfo','rrvvfo'),'same fighters must be mirrors');assert(!isMirrorMatch('rrvvfo','bark'),'different fighters must be allowed')});
await test('combines keyboard with an idle controller',()=>{const idle={axes:[0],buttons:Array.from({length:16},()=>({pressed:false}))},input=new InputManager(()=>[idle]);input.setKeyboard('KeyA',true);input.poll();assert(input.down('KeyA'),'idle gamepad cleared keyboard input')});
await test('keeps quick keyboard taps between frames',()=>{const input=new InputManager(()=>[]);input.setKeyboard('KeyH',true);input.setKeyboard('KeyH',false);input.poll();assert(input.consume('KeyH'),'quick tap was lost before polling')});
await test('applies three-hit light combo and scaling',()=>{const{one,two}=pair();for(let i=0;i<3;i++){one.attackCd=one.windup=0;one.attack('light');one.windup=0;one.resolveAttack()}assert(one.combo.hits===3,`expected 3 hits, got ${one.combo.hits}`);assert(one.combo.scale<1,'third hit did not scale')});
await test('terminates Wade ground chain at the wall',()=>{const{one,two}=pair('wade','bark');one.x=820;two.x=897;for(let i=0;i<3;i++){one.attackCd=one.windup=0;assert(one.attack('light'),`light ${i+1} did not start`);one.windup=0;assert(one.resolveAttack(),`light ${i+1} missed`)}assert(one.chainLockout>0,'final light did not lock the chain');for(let i=0;i<12;i++){one.attackCd=one.windup=0;assert(!one.attack('light'),'1-2-3 chain restarted during lockout')}assert(one.combo.hits===3,`wall loop reached ${one.combo.hits} hits`)});
await test('cancels interrupted attack startup',()=>{const{one,two}=pair('rrvvfo','wade');assert(one.attack('heavy'),'heavy did not start');assert(one.windup>0&&one.pendingMove,'startup state missing');one.hit(5,0,'light',two,{hitstun:12});assert(one.windup===0&&one.pending===null&&one.pendingMove===null&&one.queuedAttack===null,'interrupted startup survived')});
await test('launches into an air attack',()=>{const{one,two}=pair();one.attack('launcher');one.windup=0;one.resolveAttack();assert(two.vy<0,'launcher did not lift defender');one.attackCd=0;one.grounded=0;one.y=two.y-15;one.attack('air');one.windup=0;assert(one.resolveAttack(),'air follow-up did not connect')});
await test('reports actual post-defense damage',()=>{const result=calculateFinalDamage({base:20,hit:2,defense:2,armor:true,blocked:false});assert(Math.abs(result.final-4.95)<.001,`unexpected final damage ${result.final}`)});
await test('combo total equals health actually removed',()=>{const{one,two}=pair('rrvvfo','bark');two.armor=30;const before=two.hp;two.hit(20,0,'heavy',one,{hitstun:20});assert(Math.abs(one.combo.damage-(before-two.hp))<.0001,`combo ${one.combo.damage} did not match health loss ${before-two.hp}`)});
await test('fully resets Training state and delayed work',()=>{const{world,one,two}=pair();world.projectiles.push({});world.effects.add({t:'slash',l:20});world.effects.burst(1,1,'#fff');world.timers.schedule(()=>{},10000);Object.assign(one,{lens:20,armor:20,aura:20,trap:20,freeze:20,inv:20,stun:20,knockdown:20,getup:20,windup:20,attackCd:20,airDashes:1,juggles:3,lightChain:2});trainingState.enabled=true;resetTrainingWorld(world);assert(world.projectiles.length===0&&world.effects.effects.length===0&&world.effects.particles.length===0&&world.timers.size===0,'transient world state leaked');assert([one,two].every(f=>f.x===(f.side===1?150:762)&&f.lens===0&&f.attackCd===0&&f.lightChain===0),'fighter state did not reset')});
await test('cleans all state when exiting Training',()=>{const{world,one}=pair();let inputCleared=false;world.projectiles.push({});world.timers.schedule(()=>{},10000);one.lens=20;trainingState.enabled=true;trainingState.inputHistory.push('F');exitTrainingWorld(world,{clear:()=>{inputCleared=true}});assert(!trainingState.enabled&&trainingState.inputHistory.length===0&&inputCleared,'Training flags or input survived exit');assert(world.projectiles.length===0&&world.timers.size===0&&one.lens===0,'combat state survived Training exit')});
await test('canceled delayed attacks cannot leak rounds',async()=>{const timers=new TimerRegistry();let fired=0;timers.schedule(()=>fired++,10);timers.cancelAll();await new Promise(resolve=>setTimeout(resolve,25));assert(fired===0,'canceled delayed attack fired in a later round')});
await test('keeps non-CPU dummy modes stationary and passive',()=>{for(const mode of ['never','always','after','stationary']){trainingState.dummy=mode;trainingState.afterFirstHit=mode==='after';const command=dummyCommand();assert(!['a','h','x','s','u','d','j'].some(action=>command.pressed(action)),`${mode} dummy attacked`);assert(!command.down('l')&&!command.down('r'),`${mode} dummy moved`)}trainingState.dummy='never';assert(!dummyCommand().down('b'),'Never Block blocked');trainingState.dummy='always';assert(dummyCommand().down('b'),'Always Block did not block')});
await test('Bark counter punishes nearby melee only',()=>{const{one:bark,two:attacker}=pair('bark','wade');assert(bark.counter(),'counter did not start');bark.counterStartup=0;bark.counterActive=10;const barkHp=bark.hp,attackerHp=attacker.hp;bark.hit(8,0,'light',attacker,{hitstun:12});assert(bark.hp===barkHp,'Bark took melee damage during active counter');assert(attacker.hp<attackerHp,'nearby melee attacker was not punished')});
await test('Bark counter does not punish projectiles',()=>{const{one:bark,two:attacker}=pair('bark','rrvvfo');bark.counter();bark.counterStartup=0;bark.counterActive=10;const attackerHp=attacker.hp;bark.hit(8,0,'special',attacker,{hitstun:12});assert(bark.hp<100,'projectile did not hit Bark');assert(attacker.hp===attackerHp,'projectile user was remotely countered');assert(bark.counterRecovery>0,'failed counter did not enter recovery')});
await test('synchronizes Training settings',()=>{const pre={checked:true},live={checked:true};setTrainingSetting('infiniteHealth',false,pre,live);assert(!trainingState.infiniteHealth&&!pre.checked&&!live.checked,'health toggles diverged');const menu={value:'never'},hud={value:'never'};setTrainingSetting('dummy','cpu',menu,hud);assert(trainingState.dummy==='cpu'&&menu.value==='cpu'&&hud.value==='cpu','dummy selectors diverged')});
await test('Lens sacrifices 50 HP and floors at one',()=>{const{one}=pair();one.hp=34;one.en=100;one.lensAbility();assert(one.hp===1,`expected 1 HP, got ${one.hp}`);assert(one.en===10&&one.lens===240,'Lens energy or duration incorrect');assert(one.aura===0,'Flow State must remain separate')});
await test('Shots of Agony creates exactly four clones and costs 40 energy',()=>{const world=makeWorld();world.timers=new ManualTimers();const{one}=pair('rrvvfo','revvfo',world);one.en=100;assert(one.beginShotsOfAgony(),'volley did not start');assert(one.en===60,`expected 60 energy, got ${one.en}`);assert(world.effects.effects.filter(effect=>effect.t==='agonyClone').length===4,'volley did not create four clones');assert(one.agonyCooldown===0,'cooldown began before clones fired')});
await test('Shots active volley blocks reuse and suppresses regeneration',()=>{const world=makeWorld();world.timers=new ManualTimers();const{one}=pair('rrvvfo','revvfo',world);one.beginShotsOfAgony();const energy=one.en;assert(!one.beginShotsOfAgony(),'second volley started while first was active');for(let i=0;i<60;i++)one.update();assert(one.en===energy,'energy regenerated during committed volley')});
await test('Shots fires four projectiles together then starts five-second cooldown',()=>{const world=makeWorld();world.timers=new ManualTimers();const{one}=pair('rrvvfo','revvfo',world);one.beginShotsOfAgony();assert(world.timers.tasks.length===1&&world.timers.tasks[0].delay===240,'volley tell was not scheduled together');world.timers.flush();assert(world.projectiles.filter(projectile=>projectile.volleyOwner===one).length===4,'clones did not fire four simultaneous projectiles');assert(one.agonyCooldown===300,'cooldown did not start at 300 after firing')});
await test('Shots cooldown lasts the full 300 simulation frames',()=>{const{one}=pair('rrvvfo','revvfo');one.agonyCooldown=300;for(let frame=0;frame<299;frame++)one.update();assert(one.agonyCooldown===1,`cooldown expired early at ${one.agonyCooldown}`);one.update();assert(one.agonyCooldown===0,'cooldown did not expire after 300 frames')});
await test('Shots total damage stays between 25 and 30',()=>{const{one,two}=pair('rrvvfo','revvfo');const before=two.hp;for(let i=0;i<4;i++)two.hit(7.4*one.c.p,0,'special',one,{hitstun:20});const damage=before-two.hp;assert(damage>=25&&damage<=30,`four-clone damage was ${damage.toFixed(2)}`)});
await test('Phanta defense is balanced and survives every individual move',()=>{assert(ROSTER.phanta.d>=1.08&&ROSTER.phanta.d<=1.12,'Phanta defense is outside target range');for(const id of ROSTER_IDS){const{one:attacker,two:phanta}=pair(id,'phanta');for(const kind of ['light','heavy','launcher','air']){const variants=kind==='light'&&MOVESETS[id]?.light?MOVESETS[id].light:[moveFor(id,kind)||ATTACKS[kind]];for(const move of variants){phanta.hp=100;resetCombo(attacker.combo);phanta.hit(move.damage*attacker.c.p,0,kind,attacker,move);assert(phanta.hp>0,`${id} ${kind} defeated full-health Phanta`)}}for(const kind of ['special','ultimate']){phanta.hp=100;resetCombo(attacker.combo);const total=MOVE_DAMAGE_TOTALS[id][kind];if(total>0)phanta.hit(total*attacker.c.p,0,kind,attacker,{hitstun:20});assert(phanta.hp>0,`${id} ${kind} defeated full-health Phanta`)}}});
await test('every roster AI can select core offense, movement, and defense',()=>{const required=['a','h','x','s','u','d','j'];for(const id of ROSTER_IDS){const{one,two}=pair(id,id==='rrvvfo'?'bark':'rrvvfo');one.en=100;one.specialCd=one.ultCd=one.dashCd=0;one.agonyCooldown=0;one.agonyActiveVolley=false;const available=availableAIActions(one,two),profile=aiProfile(id);for(const action of required){assert(available.actions.includes(action),`${id} cannot consider ${action}`);const weighted=available.actions.map(candidate=>Math.max(.01,profile[candidate]||.01)),index=available.actions.indexOf(action),before=weighted.slice(0,index).reduce((sum,value)=>sum+value,0),roll=(before+weighted[index]/2)/weighted.reduce((sum,value)=>sum+value,0);assert(selectAIAction(available.actions,profile,roll)===action,`${id} cannot select ${action}`)}assert(available.movements.length===2,`${id} lacks movement choices`);assert(available.canBlock&&profile.block>0,`${id} lacks defensive choices`)}});
await test('all roster AI profiles are character-specific without damage modifiers',()=>{assert(Object.keys(CHARACTER_AI).length===ROSTER_IDS.length,'missing character AI profiles');for(const id of ROSTER_IDS){const profile=CHARACTER_AI[id];assert(profile?.style,`${id} lacks a documented AI style`);assert(!('damage'in profile),`${id} AI changes damage`)}});
await test('CPU Rrvvfo obeys Shots availability restrictions',()=>{const{one,two}=pair('rrvvfo','bark');one.en=100;one.agonyActiveVolley=true;assert(!availableAIActions(one,two).actions.includes('s'),'CPU considered Shots during active volley');one.agonyActiveVolley=false;one.agonyCooldown=200;assert(!availableAIActions(one,two).actions.includes('s'),'CPU considered Shots during cooldown');one.agonyCooldown=0;assert(availableAIActions(one,two).actions.includes('s'),'CPU did not consider ready Shots')});

await test('compatible heavy attacks trigger a melee clash',()=>{const{world,one,two}=pair('bark','revvfo');two.x=352;assert(two.attack('heavy')&&one.attack('heavy'),'heavy startups failed');one.windup=0;assert(one.resolveAttack(),'heavy resolution failed');assert(world.clash.active&&world.clash.type==='melee','compatible heavies did not clash')});
await test('incompatible attacks do not trigger a cinematic clash',()=>{assert(!compatibleMeleeClash('light','heavy'),'light was clash compatible');const{world,one,two}=pair();two.x=352;two.attack('heavy');one.attack('light');one.windup=0;one.resolveAttack();assert(!world.clash.active,'light versus heavy triggered a clash')});
await test('beam collisions start a beam clash',()=>{const{world,one,two}=pair('revvfo','virek');const left=new Projectile(one,470,250,2,0,'#f5f',20,16,'beam'),right=new Projectile(two,490,250,-2,0,'#5f9',20,16,'beam');world.projectiles.push(left,right);left.update(world);assert(world.clash.active&&world.clash.type==='beam','beam collision did not start a clash');assert(left.dead&&right.dead,'colliding beams remained active')});
await test('clash state clears after completion',()=>{const{world,one,two}=pair();startClash(world,'melee',one,two,{powerA:12,powerB:12});world.clash.frame=1;updateClash(world,[0,0]);assert(!world.clash.active,'completed clash stayed active');assert(one.clashCooldown===CLASH_BALANCE.cooldown,'clash cooldown was not applied')});
await test('clash state clears when a round ends',()=>{const{world,one,two}=pair();startClash(world,'ultimate',one,two,{powerA:30,powerB:30});clearClash(world);assert(!world.clash.active&&world.clash.fighters.length===0,'round cleanup retained clash state')});
await test('clash state clears during Training reset',()=>{const{world,one,two}=pair();trainingState.enabled=true;startClash(world,'melee',one,two,{powerA:12,powerB:12});resetTrainingWorld(world);assert(!world.clash.active,'Training reset retained clash state')});
await test('CPU clash input respects difficulty',()=>{const{one}=pair('bark','wade');const easy=cpuClashContribution('easy',one,0),normal=cpuClashContribution('normal',one,0),hard=cpuClashContribution('hard',one,0);assert(easy<normal&&normal<hard,`CPU clash strength did not scale: ${easy}/${normal}/${hard}`)});
await test('clash damage cannot one-shot a full-health fighter',()=>{const{world,one,two}=pair();startClash(world,'ultimate',one,two,{powerA:40,powerB:20});world.clash.meter=100;finishClash(world,1);assert(two.hp>0,`ultimate clash reduced full health to ${two.hp}`)});

await test('blocking reduces guard and applies controlled chip',()=>{const{one,two}=pair();two.block=1;const hp=two.hp,guard=two.guard;two.hit(20,5,'heavy',one,{hitstun:20});assert(two.guard<guard,'blocking did not reduce guard');assert(two.hp<hp&&two.hp>hp-5,'heavy chip was missing or excessive')});
await test('guard regenerates only when allowed',()=>{const{two}=pair();two.guard=50;two.guardRegenDelay=0;two.update();assert(two.guard>50,'idle guard did not regenerate');const after=two.guard;two.block=1;two.wasBlocking=true;two.update({down:action=>action==='b',pressed:()=>false});assert(two.guard===after,'guard regenerated while blocking')});
await test('guard break activates at zero guard',()=>{const{one,two}=pair();two.guard=1;two.block=1;two.hit(18,4,'heavy',one,{hitstun:20});assert(two.guard===0&&two.guardBreakStun>0&&!two.block,'zero guard did not cause guard break')});
await test('guard-break loops are prevented',()=>{const{one,two}=pair();two.guard=1;two.block=1;two.hit(18,4,'heavy',one,{hitstun:20});const stun=two.guardBreakStun;two.update({down:()=>true,pressed:()=>false});two.hit(5,0,'light',one,{hitstun:8});assert(!two.block&&two.guardBreakStun<=stun,'guard break immediately looped')});
await test('perfect block only works during its timing window',()=>{const command={down:action=>action==='b',pressed:()=>false};const early=pair();early.two.update(command);const earlyGuard=early.two.guard;early.two.hit(20,4,'heavy',early.one,{hitstun:20});const earlyLoss=earlyGuard-early.two.guard;const late=pair();for(let i=0;i<8;i++)late.two.update(command);const lateGuard=late.two.guard;late.two.hit(20,4,'heavy',late.one,{hitstun:20});const lateLoss=lateGuard-late.two.guard;assert(earlyLoss<lateLoss*.25,`perfect block guard loss ${earlyLoss} was not below normal ${lateLoss}`)});
await test('throws beat blocking at close range',()=>{const{one,two}=pair();two.block=1;const hp=two.hp;assert(one.throw(),'throw did not start');assert(one.resolveThrow(),'close throw did not connect');assert(two.hp<hp&&!two.block&&two.throwProtection>0,'throw did not beat block')});
await test('throws fail outside close range',()=>{const{one,two}=pair();two.x=750;const hp=two.hp;one.throw();assert(!one.resolveThrow(),'distant throw connected');assert(two.hp===hp&&one.throwRecovery>0,'distant throw was not a punishable miss')});
await test('throw protection prevents immediate repeated throws',()=>{const{one,two}=pair();one.throw();one.resolveThrow();const hp=two.hp;one.throwRecovery=one.attackCd=0;one.throw();assert(!one.resolveThrow(),'throw protection allowed an immediate rethrow');assert(two.hp===hp,'protected throw dealt damage')});
await test('combo breaker costs 85 energy and cannot be spammed',()=>{const{one}=pair();one.en=100;one.stun=24;assert(one.comboBreaker(),'breaker did not activate');assert(one.en===100-DEFENSE_BALANCE.breakerCost,'breaker energy cost was wrong');one.stun=24;assert(!one.comboBreaker(),'breaker activated twice in one round')});
await test('chip damage cannot reduce health below one',()=>{const{one,two}=pair();two.hp=1;two.block=1;two.hit(80,0,'ultimate',one,{hitstun:20});assert(two.hp===1,'blocked chip defeated the fighter')});
await test('defensive AI can retreat throw break combos and scale perfect blocks',()=>{const{one,two}=pair('creed','bark');one.guard=20;const retreat=decideCPU(one,two,'hard',()=>0);assert(retreat.move==='l','low-guard CPU did not retreat');two.block=1;assert(availableAIActions(one,two).actions.includes('t'),'CPU could not consider a throw against block');one.stun=20;one.en=100;assert(availableAIActions(one,two).actions.includes('k'),'CPU could not consider a breaker');one.stun=0;const easy=decideCPU(one,two,'easy',()=>.3),hard=decideCPU(one,two,'hard',()=>.3);assert(!easy.block&&hard.block,'perfect-block/block consistency did not scale by difficulty')});

await test('every fighter has a valid bounded cinematic ultimate',()=>{for(const id of ROSTER_IDS){const data=ULTIMATES[id];assert(data,`${id} has no ultimate`);assert(data.damage>=ULTIMATE_BALANCE.minDamage&&data.damage<=ULTIMATE_BALANCE.maxDamage,`${id} ultimate damage ${data.damage} is out of bounds`);assert(data.startup>0&&data.recovery>0&&data.duration>=120,`${id} ultimate lacks startup, recovery, or cinematic duration`)}});
await test('ultimate energy cost and cooldown are enforced',()=>{const{one}=pair();one.en=89;assert(!one.ultimate(),'ultimate activated without enough energy');one.en=100;assert(one.ultimate(),'charged ultimate did not activate');assert(one.en===10&&one.ultCd===ULTIMATE_BALANCE.cooldown,'ultimate cost or cooldown was wrong');assert(!one.ultimate(),'ultimate ignored its lockout')});
await test('missing an ultimate creates punishable recovery',()=>{const{one,two}=pair('bark','wade');one.x=80;two.x=800;one.en=100;one.ultimate();one.ultimateStartup=0;assert(!one.resolveUltimate(),'out-of-range ultimate connected');assert(one.ultimateRecovery===ULTIMATES.bark.recovery,'missed ultimate lacked recovery')});
await test('no cinematic ultimate one-shots a full-health normal fighter',()=>{for(const id of ROSTER_IDS){const opponent=id==='virek'?'bark':'virek',setup=pair(id,opponent);setup.one.x=300;setup.two.x=345;setup.one.en=100;assert(setup.one.ultimate(),`${id} ultimate did not start`);setup.one.ultimateStartup=0;setup.one.resolveUltimate();updateCinematic(setup.world);assert(setup.two.hp>0,`${id} ultimate one-shot a full-health fighter`)}});
await test('camera restores after every cinematic',()=>{for(const id of ROSTER_IDS){const setup=pair(id,id==='wade'?'bark':'wade');setup.one.x=300;setup.two.x=345;beginCinematicUltimate(setup.world,setup.one,setup.two);setup.world.cinematic.frame=1;setup.world.cinematic.impactFrame=0;updateCinematic(setup.world);assert(!setup.world.camera.active&&setup.world.camera.zoom===1,`${id} camera did not restore`)}});
await test('camera restores after cinematic interruption',()=>{const{world,one,two}=pair('revvfo','wade');world.cinematicMode='full';beginCinematicUltimate(world,one,two);assert(world.camera.active,'cinematic camera did not start');one.hit(2,0,'light',two,{hitstun:4});assert(!world.cinematic.active&&!world.camera.active,'interrupted cinematic retained camera state')});
await test('camera restores after round cleanup and Training reset',()=>{const round=pair();round.world.cinematicMode='full';beginCinematicUltimate(round.world,round.one,round.two);clearCinematic(round.world);assert(!round.world.camera.active,'round cleanup retained camera');const training=pair();training.world.cinematicMode='full';beginCinematicUltimate(training.world,training.one,training.two);trainingState.enabled=true;resetTrainingWorld(training.world);assert(!training.world.camera.active&&!training.world.cinematic.active,'Training reset retained cinematic camera')});
await test('audio hooks exist for every major combat event',()=>{for(const cue of ['lightHit','heavyHit','launcher','block','perfectBlock','guardBreak','clash','beamClash','ultimateActivate','ultimateImpact','roundStart','ko','victory'])assert(AUDIO_HOOKS[cue],`missing ${cue} audio hook`)});
await test('Rrvvfo and Revvfo ranged specials can beam clash',()=>{const{world,one,two}=pair('rrvvfo','revvfo');one.x=120;two.x=780;one.special();two.special();assert(world.projectiles.length===2&&world.projectiles.every(projectile=>projectile.type==='beam'),'rival beams were not created');for(let frame=0;frame<50&&!world.clash.active;frame++){for(const projectile of world.projectiles)projectile.update(world)}assert(world.clash.active&&world.clash.type==='beam','Rrvvfo versus Revvfo beam clash did not start')});
await test('Rrvvfo and Phanta ultimates can clash',()=>{const{world,one,two}=pair('rrvvfo','phanta');one.en=two.en=100;assert(one.ultimate()&&two.ultimate(),'rival ultimates did not activate');assert(world.clash.active&&world.clash.type==='ultimate','Rrvvfo versus Phanta did not enter an ultimate clash')});
await test('Wade versus Bark preserves speed and armor identities',()=>{const{one:wade,two:bark}=pair('wade','bark');assert(wade.c.sp>bark.c.sp,'Wade was not faster than Bark');bark.attack('heavy');assert(bark.armor>0,'Bark heavy did not activate intentional armor')});
await test('Bark perfect block remains separate from deliberate counter',()=>{const perfect=pair('bark','wade');perfect.one.update({down:action=>action==='b',pressed:()=>false});const attackerHp=perfect.two.hp;perfect.one.hit(8,0,'light',perfect.two,{hitstun:12});assert(perfect.two.hp===attackerHp,'perfect block automatically countered');const counter=pair('bark','wade');counter.one.counter();counter.one.counterStartup=0;counter.one.counterActive=10;counter.one.hit(8,0,'light',counter.two,{hitstun:12});assert(counter.two.hp<100,'deliberate counter did not punish')});
await test('Creed can evade a cinematic ultimate with timed dash invulnerability',()=>{const{world,one:attacker,two:creed}=pair('wade','creed');world.cinematicMode='off';creed.inv=12;const hp=creed.hp;beginCinematicUltimate(world,attacker,creed);updateCinematic(world);assert(creed.hp===hp,'Creed was hit during an active evasive window')});
await test('controller attack buttons contribute independently to clashes',()=>{const buttons=Array.from({length:16},()=>({pressed:false}));buttons[0].pressed=buttons[1].pressed=true;const input=new InputManager(()=>[{axes:[0],buttons}]);input.poll();assert(input.consume('KeyF')&&input.consume('KeyR'),'controller light/heavy inputs were not both available to the clash system')});
await test('Training clash reset clears active and armed states',()=>{const{world,one,two}=pair();trainingState.forceNextClash=true;startClash(world,'melee',one,two,{powerA:12,powerB:12});trainingState.forceNextClash=true;resetTrainingClash(world);assert(!world.clash.active&&!trainingState.forceNextClash,'Training clash reset left active or armed state')});

const failed=results.filter(result=>!result.pass),output=results.map(result=>`${result.pass?'PASS':'FAIL'}  ${result.name}${result.error?` — ${result.error}`:''}`).join('\n');
document.getElementById('results').textContent=`${output}\n\n${results.length-failed.length}/${results.length} passing`;document.getElementById('results').className=failed.length?'fail':'pass';
window.__SMOKE_RESULTS__={results,passed:results.length-failed.length,failed:failed.length};
if(failed.length)console.error('Smoke tests failed',failed);else console.info(`Smoke tests passed: ${results.length}`);
