import {ROSTER,ROSTER_IDS,isMirrorMatch} from '../js/roster.js';
import {InputManager} from '../js/input.js';
import {ATTACKS,TimerRegistry,calculateFinalDamage,resetCombo} from '../js/combat.js';
import {EffectSystem} from '../js/effects.js';
import {Fighter} from '../js/fighter.js';
import {CHARACTER_AI,aiProfile,availableAIActions,selectAIAction} from '../js/ai.js';
import {MOVESETS,MOVE_DAMAGE_TOTALS,moveFor} from '../js/movesets.js';
import {trainingState,resetTrainingWorld,exitTrainingWorld,setTrainingSetting,dummyCommand} from '../js/training.js';

const results=[],assert=(condition,message)=>{if(!condition)throw new Error(message)};
async function test(name,fn){try{await fn();results.push({name,pass:true})}catch(error){results.push({name,pass:false,error:error.message})}}
function makeWorld(){
  return{width:960,height:540,ground:430,fighters:[],projectiles:[],effects:new EffectSystem(),timers:new TimerRegistry(),shake:0,hitstop:0,training:trainingState,sound:()=>{}};
}
function pair(a='rrvvfo',b='revvfo',world=makeWorld()){const one=new Fighter(a,1,false,world),two=new Fighter(b,2,false,world);world.fighters=[one,two];one.x=300;two.x=345;return{world,one,two}}
class ManualTimers{constructor(){this.tasks=[]}schedule(fn,delay){this.tasks.push({fn,delay})}cancelAll(){this.tasks=[]}flush(){for(const task of this.tasks.splice(0))task.fn()}get size(){return this.tasks.length}}

await test('loads the complete roster',()=>assert(ROSTER_IDS.length===14,`expected 14, got ${ROSTER_IDS.length}`));
await test('preserves mirror-match restriction',()=>{assert(isMirrorMatch('rrvvfo','rrvvfo'),'same fighters must be mirrors');assert(!isMirrorMatch('rrvvfo','bark'),'different fighters must be allowed')});
await test('combines keyboard with an idle controller',()=>{const idle={axes:[0],buttons:Array.from({length:16},()=>({pressed:false}))},input=new InputManager(()=>[idle]);input.setKeyboard('KeyA',true);input.poll();assert(input.down('KeyA'),'idle gamepad cleared keyboard input')});
await test('keeps quick keyboard taps between frames',()=>{const input=new InputManager(()=>[]);input.setKeyboard('KeyH',true);input.setKeyboard('KeyH',false);input.poll();assert(input.consume('KeyH'),'quick tap was lost before polling')});
await test('applies three-hit light combo and scaling',()=>{const{one,two}=pair();for(let i=0;i<3;i++){one.attackCd=one.windup=0;one.attack('light');one.windup=0;one.resolveAttack()}assert(one.combo.hits===3,`expected 3 hits, got ${one.combo.hits}`);assert(one.combo.scale<1,'third hit did not scale')});
await test('terminates Wade ground chain at the wall',()=>{const{one,two}=pair('wade','bark');one.x=820;two.x=897;for(let i=0;i<3;i++){one.attackCd=one.windup=0;assert(one.attack('light'),`light ${i+1} did not start`);one.windup=0;assert(one.resolveAttack(),`light ${i+1} missed`)}assert(one.chainLockout>0,'final light did not lock the chain');for(let i=0;i<12;i++){one.attackCd=one.windup=0;assert(!one.attack('light'),'1-2-3 chain restarted during lockout')}assert(one.combo.hits===3,`wall loop reached ${one.combo.hits} hits`)});
await test('cancels interrupted attack startup',()=>{const{one,two}=pair('rrvvfo','wade');assert(one.attack('heavy'),'heavy did not start');assert(one.windup>0&&one.pendingMove,'startup state missing');one.hit(5,0,'light',two,{hitstun:12});assert(one.windup===0&&one.pending===null&&one.pendingMove===null&&one.queuedAttack===null,'interrupted startup survived')});
await test('launches into an air attack',()=>{const{one,two}=pair();one.attack('launcher');one.windup=0;one.resolveAttack();assert(two.vy<0,'launcher did not lift defender');one.attackCd=0;one.grounded=0;one.y=two.y-15;one.attack('air');one.windup=0;assert(one.resolveAttack(),'air follow-up did not connect')});
await test('reports actual post-defense damage',()=>{const result=calculateFinalDamage({base:20,hit:2,defense:2,armor:true,blocked:false});assert(Math.abs(result.final-4.95)<.001,`unexpected final damage ${result.final}`)});
await test('combo total equals health actually removed',()=>{const{one,two}=pair('rrvvfo','bark');two.armor=30;const before=two.hp;two.hit(20,0,'heavy',one,{hitstun:20});assert(Math.abs(one.combo.damage-(before-two.hp))<.0001,`combo ${one.combo.damage} did not match health loss ${before-two.hp}`)});
await test('fully resets Training state and delayed work',()=>{const{world,one,two}=pair();world.projectiles.push({});world.effects.add({t:'slash',l:20});world.effects.burst(1,1,'#fff');world.timers.schedule(()=>{},10000);Object.assign(one,{lens:20,armor:20,aura:20,trap:20,freeze:20,inv:20,stun:20,knockdown:20,getup:20,windup:20,attackCd:20,airDashes:1,juggles:3,lightChain:2});trainingState.enabled=true;resetTrainingWorld(world);assert(world.projectiles.length===0&&world.effects.effects.length===0&&world.effects.particles.length===0&&world.timers.size===0,'transient world state leaked');assert([one,two].every(f=>f.x===(f.side===1?150:762)&&f.lens===0&&f.attackCd===0&&f.lightChain===0),'fighter state did not reset')});
await test('cleans all state when exiting Training',()=>{const{world,one}=pair();let inputCleared=false;world.projectiles.push({});world.timers.schedule(()=>{},10000);one.lens=20;trainingState.enabled=true;trainingState.inputHistory.push('F');exitTrainingWorld(world,{clear:()=>{inputCleared=true}});assert(!trainingState.enabled&&trainingState.inputHistory.length===0&&inputCleared,'Training flags or input survived exit');assert(world.projectiles.length===0&&world.timers.size===0&&one.lens===0,'combat state survived Training exit')});
await test('canceled delayed attacks cannot leak rounds',async()=>{const timers=new TimerRegistry();let fired=0;timers.schedule(()=>fired++,10);timers.cancelAll();await new Promise(resolve=>setTimeout(resolve,25));assert(fired===0,'canceled delayed attack fired in a later round')});
await test('keeps non-CPU dummy modes stationary and passive',()=>{for(const mode of ['never','always','after','stationary']){trainingState.dummy=mode;trainingState.afterFirstHit=mode==='after';const command=dummyCommand();assert(!['a','h','x','s','u','d','j'].some(action=>command.pressed(action)),`${mode} dummy attacked`);assert(!command.down('l')&&!command.down('r'),`${mode} dummy moved`)}trainingState.dummy='never';assert(!dummyCommand().down('b'),'Never Block blocked');trainingState.dummy='always';assert(dummyCommand().down('b'),'Always Block did not block')});
await test('Bark counter punishes nearby melee only',()=>{const{one:bark,two:attacker}=pair('bark','wade');assert(bark.counter(),'counter did not start');bark.counterStartup=0;bark.counterActive=10;const barkHp=bark.hp,attackerHp=attacker.hp;bark.hit(8,0,'light',attacker,{hitstun:12});assert(bark.hp===barkHp,'Bark took melee damage during active counter');assert(attacker.hp<attackerHp,'nearby melee attacker was not punished')});
await test('Bark counter does not punish projectiles',()=>{const{one:bark,two:attacker}=pair('bark','rrvvfo');bark.counter();bark.counterStartup=0;bark.counterActive=10;const attackerHp=attacker.hp;bark.hit(8,0,'special',attacker,{hitstun:12});assert(bark.hp<100,'projectile did not hit Bark');assert(attacker.hp===attackerHp,'projectile user was remotely countered');assert(bark.counterRecovery>0,'failed counter did not enter recovery')});
await test('synchronizes Training settings',()=>{const pre={checked:true},live={checked:true};setTrainingSetting('infiniteHealth',false,pre,live);assert(!trainingState.infiniteHealth&&!pre.checked&&!live.checked,'health toggles diverged');const menu={value:'never'},hud={value:'never'};setTrainingSetting('dummy','cpu',menu,hud);assert(trainingState.dummy==='cpu'&&menu.value==='cpu'&&hud.value==='cpu','dummy selectors diverged')});
await test('Lens sacrifices 50 HP and floors at one',()=>{const{one}=pair();one.hp=34;one.en=100;one.ultimate();assert(one.hp===1,`expected 1 HP, got ${one.hp}`);assert(one.en===10&&one.lens===240,'Lens energy or duration incorrect');assert(one.aura===0,'Flow State must remain separate')});
await test('Shots of Agony creates exactly four clones and costs 40 energy',()=>{const world=makeWorld();world.timers=new ManualTimers();const{one}=pair('rrvvfo','revvfo',world);one.en=100;assert(one.beginShotsOfAgony(),'volley did not start');assert(one.en===60,`expected 60 energy, got ${one.en}`);assert(world.effects.effects.filter(effect=>effect.t==='agonyClone').length===4,'volley did not create four clones');assert(one.agonyCooldown===0,'cooldown began before clones fired')});
await test('Shots active volley blocks reuse and suppresses regeneration',()=>{const world=makeWorld();world.timers=new ManualTimers();const{one}=pair('rrvvfo','revvfo',world);one.beginShotsOfAgony();const energy=one.en;assert(!one.beginShotsOfAgony(),'second volley started while first was active');for(let i=0;i<60;i++)one.update();assert(one.en===energy,'energy regenerated during committed volley')});
await test('Shots fires four projectiles together then starts five-second cooldown',()=>{const world=makeWorld();world.timers=new ManualTimers();const{one}=pair('rrvvfo','revvfo',world);one.beginShotsOfAgony();assert(world.timers.tasks.length===1&&world.timers.tasks[0].delay===240,'volley tell was not scheduled together');world.timers.flush();assert(world.projectiles.filter(projectile=>projectile.volleyOwner===one).length===4,'clones did not fire four simultaneous projectiles');assert(one.agonyCooldown===300,'cooldown did not start at 300 after firing')});
await test('Shots cooldown lasts the full 300 simulation frames',()=>{const{one}=pair('rrvvfo','revvfo');one.agonyCooldown=300;for(let frame=0;frame<299;frame++)one.update();assert(one.agonyCooldown===1,`cooldown expired early at ${one.agonyCooldown}`);one.update();assert(one.agonyCooldown===0,'cooldown did not expire after 300 frames')});
await test('Shots total damage stays between 25 and 30',()=>{const{one,two}=pair('rrvvfo','revvfo');const before=two.hp;for(let i=0;i<4;i++)two.hit(7.4*one.c.p,0,'special',one,{hitstun:20});const damage=before-two.hp;assert(damage>=25&&damage<=30,`four-clone damage was ${damage.toFixed(2)}`)});
await test('Phanta defense is balanced and survives every individual move',()=>{assert(ROSTER.phanta.d>=1.08&&ROSTER.phanta.d<=1.12,'Phanta defense is outside target range');for(const id of ROSTER_IDS){const{one:attacker,two:phanta}=pair(id,'phanta');for(const kind of ['light','heavy','launcher','air']){const variants=kind==='light'&&MOVESETS[id]?.light?MOVESETS[id].light:[moveFor(id,kind)||ATTACKS[kind]];for(const move of variants){phanta.hp=100;resetCombo(attacker.combo);phanta.hit(move.damage*attacker.c.p,0,kind,attacker,move);assert(phanta.hp>0,`${id} ${kind} defeated full-health Phanta`)}}for(const kind of ['special','ultimate']){phanta.hp=100;resetCombo(attacker.combo);const total=MOVE_DAMAGE_TOTALS[id][kind];if(total>0)phanta.hit(total*attacker.c.p,0,kind,attacker,{hitstun:20});assert(phanta.hp>0,`${id} ${kind} defeated full-health Phanta`)}}});
await test('every roster AI can select core offense, movement, and defense',()=>{const required=['a','h','x','s','u','d','j'];for(const id of ROSTER_IDS){const{one,two}=pair(id,id==='rrvvfo'?'bark':'rrvvfo');one.en=100;one.specialCd=one.ultCd=one.dashCd=0;one.agonyCooldown=0;one.agonyActiveVolley=false;const available=availableAIActions(one,two),profile=aiProfile(id);for(const action of required){assert(available.actions.includes(action),`${id} cannot consider ${action}`);const weighted=available.actions.map(candidate=>Math.max(.01,profile[candidate]||.01)),index=available.actions.indexOf(action),before=weighted.slice(0,index).reduce((sum,value)=>sum+value,0),roll=(before+weighted[index]/2)/weighted.reduce((sum,value)=>sum+value,0);assert(selectAIAction(available.actions,profile,roll)===action,`${id} cannot select ${action}`)}assert(available.movements.length===2,`${id} lacks movement choices`);assert(available.canBlock&&profile.block>0,`${id} lacks defensive choices`)}});
await test('all roster AI profiles are character-specific without damage modifiers',()=>{assert(Object.keys(CHARACTER_AI).length===ROSTER_IDS.length,'missing character AI profiles');for(const id of ROSTER_IDS){const profile=CHARACTER_AI[id];assert(profile?.style,`${id} lacks a documented AI style`);assert(!('damage'in profile),`${id} AI changes damage`)}});
await test('CPU Rrvvfo obeys Shots availability restrictions',()=>{const{one,two}=pair('rrvvfo','bark');one.en=100;one.agonyActiveVolley=true;assert(!availableAIActions(one,two).actions.includes('s'),'CPU considered Shots during active volley');one.agonyActiveVolley=false;one.agonyCooldown=200;assert(!availableAIActions(one,two).actions.includes('s'),'CPU considered Shots during cooldown');one.agonyCooldown=0;assert(availableAIActions(one,two).actions.includes('s'),'CPU did not consider ready Shots')});

const failed=results.filter(result=>!result.pass),output=results.map(result=>`${result.pass?'PASS':'FAIL'}  ${result.name}${result.error?` — ${result.error}`:''}`).join('\n');
document.getElementById('results').textContent=`${output}\n\n${results.length-failed.length}/${results.length} passing`;document.getElementById('results').className=failed.length?'fail':'pass';
window.__SMOKE_RESULTS__={results,passed:results.length-failed.length,failed:failed.length};
if(failed.length)console.error('Smoke tests failed',failed);else console.info(`Smoke tests passed: ${results.length}`);
