import {WORLD_REGIONS,WORLD_REGION_LINKS,WORLD_SHORTCUTS,normalizeConnectedWorldState,worldMapSummary} from './connected-world.js?v=29a4072r-ch1-adventure-playtestlab-20260802';
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
const REGION_TONES=Object.freeze({
  training:{sky:'#d8efff',land:'#9ac47c',route:'#d0ad78',water:'#6fb7df',accent:'#e9ba5d'},
  tournament:{sky:'#d9efff',land:'#f1dba4',route:'#b97662',water:'#75b9df',accent:'#d94b52'},
  resonance:{sky:'#c8d6dd',land:'#607985',route:'#92a9b3',water:'#5ec1d5',accent:'#69e0da'},
  echo:{sky:'#d9edf3',land:'#8ca47f',route:'#a78663',water:'#5fa7b4',accent:'#9bdbe4'}
});

export class StoryMap{
  constructor({title='AREA MAP',bounds={minX:-1600,maxX:1600,minZ:-1100,maxZ:1100},getPlayer=()=>null,getObjective=()=>null,getPoints=()=>[],regionId='',zoneId='',getZoneId=null,getWorldState=()=>null,getProgress=()=>({})}={}){
    this.title=title;this.bounds=bounds;this.getPlayer=getPlayer;this.getObjective=getObjective;this.getPoints=getPoints;this.regionId=regionId;this.zoneId=zoneId;this.getZoneId=typeof getZoneId==='function'?getZoneId:()=>this.zoneId;this.getWorldState=getWorldState;this.getProgress=getProgress;this.lastUpdate=0;this.view=regionId?'region':'local';this.localOnly=false;
    this.button=document.createElement('button');this.button.type='button';this.button.className='storyExplorationMapButton';this.button.textContent='MAP';this.button.setAttribute('aria-label','Open map');
    this.mini=document.createElement('aside');this.mini.className='storyMiniMap';this.mini.innerHTML='<canvas width="320" height="320" aria-label="Mini map"></canvas><strong>OBJECTIVE</strong><span data-map-objective>Explore the area</span><div class="storyMapLegend" aria-label="Map legend"><span><i data-map-symbol="player">▲</i>YOU</span><span><i data-map-symbol="objective">◆</i>GOAL</span><span><i data-map-symbol="landmark">●</i>PLACE</span><span><i data-map-symbol="optional">■</i>OPTIONAL</span></div>';
    this.overlay=document.createElement('section');this.overlay.className='storyMapOverlay';this.overlay.hidden=true;this.overlay.innerHTML=`<article class="connectedMapCard" role="dialog" aria-modal="true" aria-label="${title}"><header><div class="connectedMapHeaderText"><small data-map-region-label>${regionId?WORLD_REGIONS[regionId]?.name||'REGION MAP':'AREA MAP'}</small><h2 data-map-title>${title}</h2></div><div class="connectedMapTabs"><button type="button" data-map-tab="local">LOCAL</button>${regionId?'<button type="button" data-map-tab="region">REGION</button><button type="button" data-map-tab="world">WORLD</button>':''}<button type="button" data-map-close>CLOSE</button></div></header><div class="connectedMapMeta"><span data-map-meta-left>DISCOVER THE WORLD BY EXPLORING</span><span data-map-meta-right>HIDDEN ROUTES STAY HIDDEN</span></div><canvas class="connectedRegionCanvas" width="960" height="600"></canvas><small class="mapDiscoveryHint">Permanent shortcuts are drawn only after you open them. Unvisited areas stay vague.</small></article>`;
    this.compass=document.createElement('div');this.compass.className='storyObjectiveCompass';this.compass.innerHTML='<i data-objective-arrow>↑</i><span data-objective-copy>CURRENT OBJECTIVE</span>';
    document.body.append(this.button,this.mini,this.overlay,this.compass);
    this.button.addEventListener('click',()=>this.open());this.mini.addEventListener('click',()=>this.open());this.overlay.querySelector('[data-map-close]').addEventListener('click',()=>this.close());
    this.overlay.querySelectorAll('[data-map-tab]').forEach(button=>button.addEventListener('click',()=>{this.view=button.dataset.mapTab;this.draw(true)}));
    this.keyHandler=e=>{if(!this.overlay.hidden&&e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();this.close()}};document.addEventListener('keydown',this.keyHandler,true);this.draw(true);
  }
  setRegion(regionId,zoneId=''){this.localOnly=false;this.regionId=regionId||this.regionId;this.zoneId=zoneId||this.zoneId;if(this.defaultBounds)this.bounds={...this.defaultBounds};if(this.defaultTitle)this.title=this.defaultTitle;this.overlay.querySelectorAll('[data-map-tab="region"],[data-map-tab="world"]').forEach(button=>button.hidden=false);if(this.view!=='world')this.view=this.regionId?'region':'local';this.draw(true)}
  setLocalArea({title='',bounds=null}={}){this.localOnly=true;if(!this.defaultBounds)this.defaultBounds={...this.bounds};if(!this.defaultTitle)this.defaultTitle=this.title;if(title)this.title=title;if(bounds)this.bounds={...bounds};this.view='local';this.overlay.querySelectorAll('[data-map-tab="region"],[data-map-tab="world"]').forEach(button=>button.hidden=true);this.draw(true)}
  worldToMap(point,canvas){const b=this.bounds,pad=28,width=Math.max(1,b.maxX-b.minX),height=Math.max(1,b.maxZ-b.minZ);return{x:clamp(pad+(Number(point.x||0)-b.minX)/width*(canvas.width-pad*2),pad,canvas.width-pad),y:clamp(pad+(Number(point.z||0)-b.minZ)/height*(canvas.height-pad*2),pad,canvas.height-pad)}}
  draw(force=false){const now=performance.now();if(!force&&now-this.lastUpdate<100)return;this.lastUpdate=now;this.drawLocalCanvas(this.mini.querySelector('canvas'),false);if(!this.overlay.hidden){if(this.view==='world')this.drawWorldCanvas(this.overlay.querySelector('canvas'));else if(this.view==='region'&&this.regionId)this.drawRegionCanvas(this.overlay.querySelector('canvas'));else this.drawLocalCanvas(this.overlay.querySelector('canvas'),true)}const player=this.getPlayer(),objective=this.getObjective(),label=objective?.label||objective?.name||'Explore the area';this.mini.querySelector('[data-map-objective]').textContent=label;this.compass.querySelector('[data-objective-copy]').textContent=label;if(player&&objective){const angle=Math.atan2(objective.x-player.x,-(objective.z-player.z))*180/Math.PI;this.compass.querySelector('[data-objective-arrow]').style.transform=`rotate(${angle}deg)`}this.refreshOverlayText()}
  refreshOverlayText(){if(this.overlay.hidden)return;this.overlay.querySelectorAll('[data-map-tab]').forEach(button=>button.classList.toggle('isActive',button.dataset.mapTab===this.view));const region=WORLD_REGIONS[this.regionId],zoneId=this.getZoneId?.()||this.zoneId,zone=region?.zones?.[zoneId],state=normalizeConnectedWorldState(this.getWorldState?.()||this.getProgress?.()?.worldState||{},this.getProgress?.()||{});const title=this.overlay.querySelector('[data-map-title]'),regionLabel=this.overlay.querySelector('[data-map-region-label]'),left=this.overlay.querySelector('[data-map-meta-left]'),right=this.overlay.querySelector('[data-map-meta-right]');if(this.view==='world'){title.textContent='CONNECTED WORLD';regionLabel.textContent='RRVVFO’S JOURNEY';left.textContent=`${state.discoveredRegions.length} / ${Object.keys(WORLD_REGIONS).length} regions discovered`;right.textContent=`${state.shortcuts.length} permanent shortcuts opened`}else if(this.view==='region'&&region){title.textContent=region.name;regionLabel.textContent=region.chapterRange;const known=state.discoveredZones.filter(key=>key.startsWith(`${region.id}:`)).length;left.textContent=`${known} / ${Object.keys(region.zones).length} areas mapped`;right.textContent=zone?`YOU ARE IN • ${zone.name}`:'EXPLORE TO FILL THE MAP'}else{title.textContent=this.title;regionLabel.textContent=this.localOnly?'INTERIOR MAP':zone?.name||'LOCAL AREA';left.textContent='LOCAL POSITION + OBJECTIVE';right.textContent=this.localOnly?'EXIT THROUGH THE DOOR TO RETURN OUTSIDE':'OPEN REGION VIEW TO SEE CONNECTIONS'}}
  drawLocalCanvas(canvas,large){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#dff1ff';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#080808';ctx.lineWidth=large?7:5;ctx.strokeRect(15,15,w-30,h-30);ctx.strokeStyle='rgba(8,8,8,.13)';ctx.lineWidth=2;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(15+(w-30)*i/5,15);ctx.lineTo(15+(w-30)*i/5,h-15);ctx.stroke();ctx.beginPath();ctx.moveTo(15,15+(h-30)*i/5);ctx.lineTo(w-15,15+(h-30)*i/5);ctx.stroke()}const points=(this.getPoints()||[]).filter(point=>point&&!point.hidden);for(const point of points){const p=this.worldToMap(point,canvas),size=large?10:6,kind=point.kind||'landmark';ctx.save();ctx.translate(p.x,p.y);ctx.beginPath();ctx.fillStyle=point.color||(kind==='optional'?'#8a63ce':kind==='route'?'#3f9f78':'#61758a');ctx.strokeStyle='#080808';ctx.lineWidth=large?3:2;if(kind==='optional')ctx.rect(-size,-size,size*2,size*2);else if(kind==='route'){ctx.moveTo(0,-size-2);ctx.lineTo(size+2,0);ctx.lineTo(0,size+2);ctx.lineTo(-size-2,0);ctx.closePath()}else ctx.arc(0,0,size,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();if(large&&point.label){ctx.fillStyle='#080808';ctx.font='bold 16px Arial';ctx.fillText(point.label,p.x+14,p.y+5)}}const objective=this.getObjective();if(objective){const p=this.worldToMap(objective,canvas),size=large?17:10;ctx.save();ctx.translate(p.x,p.y);ctx.beginPath();ctx.fillStyle='#ffd557';ctx.strokeStyle='#080808';ctx.lineWidth=3;ctx.moveTo(0,-size);ctx.lineTo(size,0);ctx.lineTo(0,size);ctx.lineTo(-size,0);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();if(large){ctx.fillStyle='#080808';ctx.font='900 18px Arial';ctx.fillText(objective.label||objective.name||'OBJECTIVE',p.x+22,p.y+6)}}const player=this.getPlayer();if(player){const p=this.worldToMap(player,canvas);ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='#d9232f';ctx.strokeStyle='#080808';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,-(large?17:11));ctx.lineTo(large?12:8,large?12:8);ctx.lineTo(-(large?12:8),large?12:8);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}}
  drawRegionBackdrop(ctx,w,h,regionId){const tone=REGION_TONES[regionId]||REGION_TONES.training;ctx.fillStyle=tone.sky;ctx.fillRect(0,0,w,h);ctx.fillStyle=tone.land;ctx.beginPath();ctx.moveTo(35,h*.67);ctx.quadraticCurveTo(w*.12,h*.25,w*.32,h*.38);ctx.quadraticCurveTo(w*.48,h*.08,w*.63,h*.30);ctx.quadraticCurveTo(w*.84,h*.16,w-35,h*.47);ctx.lineTo(w-35,h-35);ctx.lineTo(35,h-35);ctx.closePath();ctx.fill();if(regionId==='echo'){ctx.strokeStyle=tone.water;ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(w*.36,h*.82);ctx.bezierCurveTo(w*.45,h*.68,w*.38,h*.54,w*.51,h*.46);ctx.stroke();ctx.fillStyle='rgba(255,255,255,.55)';for(const [x,y] of [[.68,.22],[.75,.15],[.82,.10]]){ctx.beginPath();ctx.moveTo(w*x-34,h*y+34);ctx.lineTo(w*x,h*y-28);ctx.lineTo(w*x+34,h*y+34);ctx.closePath();ctx.fill()}}else if(regionId==='tournament'){ctx.fillStyle='rgba(255,255,255,.7)';ctx.beginPath();ctx.arc(w*.73,h*.48,76,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#b94a51';ctx.lineWidth=10;ctx.stroke()}else if(regionId==='resonance'){ctx.fillStyle='rgba(20,35,43,.24)';for(let x=70;x<w;x+=110)ctx.fillRect(x,70,58,h-140)}else{ctx.strokeStyle=tone.water;ctx.lineWidth=14;ctx.beginPath();ctx.moveTo(w*.12,h*.78);ctx.bezierCurveTo(w*.32,h*.70,w*.43,h*.53,w*.59,h*.66);ctx.stroke()}ctx.strokeStyle='#080808';ctx.lineWidth=7;ctx.strokeRect(15,15,w-30,h-30)}
  drawRegionCanvas(canvas){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,region=WORLD_REGIONS[this.regionId];if(!region){this.drawLocalCanvas(canvas,true);return}this.drawRegionBackdrop(ctx,w,h,region.id);const progress=this.getProgress?.()||{},state=normalizeConnectedWorldState(this.getWorldState?.()||progress.worldState||{},progress),known=new Set(state.discoveredZones),current=this.getZoneId?.()||this.zoneId;const coords=id=>{const map=region.zones[id]?.map||{x:0,y:0};return{x:map.x/900*w,y:map.y/560*h}};ctx.lineCap='round';for(const [a,b] of region.links){const ka=known.has(`${region.id}:${a}`),kb=known.has(`${region.id}:${b}`);if(!ka&&!kb)continue;const pa=coords(a),pb=coords(b);ctx.strokeStyle=ka&&kb?'rgba(26,28,30,.58)':'rgba(26,28,30,.18)';ctx.lineWidth=ka&&kb?7:4;ctx.setLineDash(ka&&kb?[]:[10,12]);ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke()}ctx.setLineDash([]);for(const id of state.shortcuts){const sc=WORLD_SHORTCUTS[id];if(sc?.region!==region.id)continue;const a=coords(sc.from),b=coords(sc.to);ctx.strokeStyle='#8b58c7';ctx.lineWidth=6;ctx.setLineDash([8,7]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}ctx.setLineDash([]);const adjacent=new Set();for(const [a,b] of region.links){if(known.has(`${region.id}:${a}`))adjacent.add(b);if(known.has(`${region.id}:${b}`))adjacent.add(a)}for(const zone of Object.values(region.zones)){const key=`${region.id}:${zone.id}`,isKnown=known.has(key),isHint=!isKnown&&adjacent.has(zone.id);if(!isKnown&&!isHint)continue;const p=coords(zone.id),size=zone.kind==='landmark'?14:zone.kind==='hub'?12:10;ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle=isKnown?(zone.id===current?'#ff5b4e':zone.kind==='secret'?'#9b6ac7':'#fff1b8'):'#d0c9b8';ctx.strokeStyle='#080808';ctx.lineWidth=3;if(isHint){ctx.beginPath();ctx.arc(0,0,9,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#080808';ctx.font='900 15px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('?',0,1)}else{ctx.beginPath();if(zone.kind==='building'||zone.kind==='room')ctx.rect(-size,-size,size*2,size*2);else{ctx.arc(0,0,size,0,Math.PI*2)}ctx.fill();ctx.stroke()}ctx.restore();if(isKnown){ctx.fillStyle='#080808';ctx.font=`900 ${zone.id===current?18:14}px Arial`;ctx.textAlign='center';ctx.fillText(zone.name,p.x,p.y+size+21)}}}
  drawWorldCanvas(canvas){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,progress=this.getProgress?.()||{},state=normalizeConnectedWorldState(this.getWorldState?.()||progress.worldState||{},progress),summary=worldMapSummary({...progress,worldState:state});ctx.clearRect(0,0,w,h);ctx.fillStyle='#dcebf1';ctx.fillRect(0,0,w,h);ctx.fillStyle='#86b5cf';ctx.fillRect(0,h*.58,w,h*.42);ctx.strokeStyle='rgba(255,255,255,.55)';ctx.lineWidth=8;for(let y=h*.62;y<h;y+=36){ctx.beginPath();ctx.moveTo(0,y);ctx.bezierCurveTo(w*.25,y-15,w*.5,y+15,w*.75,y-8);ctx.bezierCurveTo(w*.85,y-20,w*.95,y+10,w,y);ctx.stroke()}const pos=id=>{const p=WORLD_REGIONS[id].world;return{x:p.x/900*w,y:p.y/560*h}};for(const link of WORLD_REGION_LINKS){const a=summary.find(r=>r.id===link.from),b=summary.find(r=>r.id===link.to);if(!a?.known&&!b?.known)continue;const pa=pos(link.from),pb=pos(link.to);ctx.strokeStyle=link.type==='teleporter'?'#7c68c8':'#463d35';ctx.lineWidth=8;ctx.setLineDash(link.type==='teleporter'?[14,10]:[]);ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke()}ctx.setLineDash([]);for(const item of summary){if(!item.known)continue;const region=WORLD_REGIONS[item.id],p=pos(item.id),tone=REGION_TONES[item.id]||REGION_TONES.training;ctx.fillStyle=tone.land;ctx.strokeStyle='#080808';ctx.lineWidth=item.current?7:4;ctx.beginPath();ctx.arc(p.x,p.y,item.current?42:34,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#080808';ctx.font=`900 ${item.current?20:17}px Arial`;ctx.textAlign='center';ctx.fillText(region.short,p.x,p.y+60);ctx.font='800 12px Arial';ctx.fillText(`${item.zonesKnown}/${item.zonesTotal} MAPPED`,p.x,p.y+78)}ctx.strokeStyle='#080808';ctx.lineWidth=7;ctx.strokeRect(15,15,w-30,h-30)}
  setVisible(visible=true){this.button.hidden=!visible;this.mini.hidden=!visible;this.compass.hidden=!visible;if(!visible)this.overlay.hidden=true}
  open(){this.overlay.hidden=false;if(this.regionId&&this.view==='local'&&!this.localOnly)this.view='region';this.draw(true);this.overlay.querySelector('[data-map-close]').focus()}
  close(){this.overlay.hidden=true;this.button.focus()}
  destroy(){document.removeEventListener('keydown',this.keyHandler,true);this.button.remove();this.mini.remove();this.overlay.remove();this.compass.remove()}
}
